# Generated by Django 4.2.26 on 2025-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_jobapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Offer', 'Offer')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
