# Generated by Django 4.2.26 on 2025-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Careers Website', 'Careers Website'), ('Other', 'Other')], default='Careers Website', max_length=20),
        ),
    ]
