# Generated by Django 4.2.26 on 2025-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Ghosted', 'Ghosted'), ('Avoid', 'Avoid'), ('Rejected', 'Rejected'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Offer', 'Offer')], default='Applied', max_length=20),
        ),
    ]
