# Generated by Django 4.2.26 on 2025-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="workflows",
            field=models.ManyToManyField(
                blank=True, related_name="job_applications", to="jobs.workflow"
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
