# Generated by Django 4.2.26 on 2025-12-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_workexperience_workachievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Responsability"),
                            (2, "Requirement"),
                            (3, "Company Research"),
                            (4, "Role Research"),
                        ]
                    ),
                ),
                ("info", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_data",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
        ),
    ]
