# Generated by Django 4.2.26 on 2025-12-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_researchdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Preparing Application", "Preparing Application"),
                    ("Applied", "Applied"),
                    ("Ghosted", "Ghosted"),
                    ("Avoid", "Avoid"),
                    ("Rejected", "Rejected"),
                    ("Technical Interview", "Technical Interview"),
                    ("HR Interview", "HR Interview"),
                    ("Offer", "Offer"),
                ],
                default="Preparing Application",
                max_length=30,
            ),
        ),
    ]
