# Generated by Django 4.2.26 on 2025-12-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_add_preparing_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, default=""),
        ),
    ]
