# Generated by Django 4.2.26 on 2025-12-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_jobapplication_cover_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
